In [5]:
import pandas as pd
import chardet

# 检测文件编码
with open('jd1.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
    print(f"文件编码格式为: {result['encoding']}")

# 使用检测到的编码读取
df = pd.read_csv('jd1.csv', encoding=encoding)
df

文件编码格式为: UTF-8-SIG

,用户名,评分,评论时间,评论内容
0,T***M,5,2026-01-23 00:14:49,配料表里没有猪肉，纯虾肉。味道很鲜美，一盒有上下两层馄饨，6袋调味包。我就喜欢这种皮薄的，皮...
1,j***u,5,2026-01-28 09:43:03,正大食品质量好，值得信赖。玉米蔬菜猪肉蒸饺薄皮大馅，汁水丰富。蒸着吃好吃，煎着吃更香。份量很...
2,j***6,5,2026-01-27 19:09:13,一共二十四个，个头不小，馅料也很足，很容易煮熟，差不多开锅就熟，不要久煮饺子皮容易破。做煎饺...
3,雨***虹,5,2026-01-13 07:39:43,正大食品，知名品牌，食品安全有保障。这款虾饺，皮儿薄馅儿大，选用南美白对虾，鲜美可口，煎、炸...
4,jd_156357gta,5,2025-12-30 12:21:31,这韭菜盒子真的是让我惊艳到了！外皮烤得恰到好处，酥脆而不油腻，轻轻一咬，就能感受到那层层的酥...
...,...,...,...,...
328,2***n,5,2025-11-14 13:08:29,挺好吃的价钱实惠早饭吃了
329,j***x,5,2025-12-03 18:00:34,味道口感都不错，多次回购了。
330,u_noso89pgwboi,5,2025-11-22 11:41:02,很好吃哦，很干净啊.很便宜。。
331,jd_hurl01,5,2025-12-20 12:32:12,冬至了，懒得包，挺方便的。
332,Mio不想说话,5,2025-11-14 08:28:55,大个，包装完好，送货快。

In [6]:
#删除数据集里面的重复行
df.drop_duplicates(inplace=True)
df.to_csv('jd1.csv',index=False, encoding='utf-8-sig')
df

,用户名,评分,评论时间,评论内容
0,T***M,5,2026-01-23 00:14:49,配料表里没有猪肉，纯虾肉。味道很鲜美，一盒有上下两层馄饨，6袋调味包。我就喜欢这种皮薄的，皮...
1,j***u,5,2026-01-28 09:43:03,正大食品质量好，值得信赖。玉米蔬菜猪肉蒸饺薄皮大馅，汁水丰富。蒸着吃好吃，煎着吃更香。份量很...
2,j***6,5,2026-01-27 19:09:13,一共二十四个，个头不小，馅料也很足，很容易煮熟，差不多开锅就熟，不要久煮饺子皮容易破。做煎饺...
3,雨***虹,5,2026-01-13 07:39:43,正大食品，知名品牌，食品安全有保障。这款虾饺，皮儿薄馅儿大，选用南美白对虾，鲜美可口，煎、炸...
4,jd_156357gta,5,2025-12-30 12:21:31,这韭菜盒子真的是让我惊艳到了！外皮烤得恰到好处，酥脆而不油腻，轻轻一咬，就能感受到那层层的酥...
...,...,...,...,...
298,j***y,5,2026-01-07 22:03:45,好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃好吃...
299,恋***l,5,2025-03-03 12:27:33,包装完好物美价廉好好好好
300,1***9,5,2025-02-07 10:36:03,OKOKOKOKOKOK哦哦OKOKOK哦哦吗
301,_***c,5,2024-06-10 15:04:28,👌🏻挺好的哦噢噢哦哦哦噢噢噢噢哦哦
302,0***2,5,2024-07-06 10:57:47,质量很好服务好十分感谢！